---
- name: Create Hub configuration file
  template:
    dest: "{{selenium_config_path}}/hub.json"
    src: hub.json.j2
    mode: 0644
  when: selenium_hub_enabled


- name: Create Node configuration file
  template:
    dest: "{{selenium_config_path}}/node.json"
    src: node.json.j2
    mode: 0644
  when: selenium_node_enabled
